In [8]:
from sklearn.feature_extraction.text import CountVectorizer
import numpy as np
from sklearn.feature_extraction.text import TfidfVectorizer 


In [15]:

content = ["Human machine interface for, Lab ABC computer applications",
"A survey of user opinion. of computer system response time",
"The EPS user interface, management system"
"System and human system, engineering testing of EPS",
"Relation of user-perceived response time to error measurement",
"The generation of random, binary, unordered trees",
"The intersection graph, of paths in trees",
"Graph minors IV: Widths of trees and well-quasi-ordering",
"Graph minors: A survey"]


In [16]:
tfidf = TfidfVectorizer()

In [17]:
result = tfidf.fit_transform(content)

In [18]:
print('\nWord indexes:') 
print(tfidf.vocabulary_)


Word indexes:
{'human': 11, 'machine': 17, 'interface': 13, 'for': 8, 'lab': 16, 'abc': 0, 'computer': 4, 'applications': 2, 'survey': 30, 'of': 21, 'user': 39, 'opinion': 22, 'system': 31, 'response': 29, 'time': 35, 'the': 34, 'eps': 6, 'management': 18, 'systemsystem': 32, 'and': 1, 'engineering': 5, 'testing': 33, 'relation': 28, 'perceived': 25, 'to': 36, 'error': 7, 'measurement': 19, 'generation': 9, 'random': 27, 'binary': 3, 'unordered': 38, 'trees': 37, 'intersection': 14, 'graph': 10, 'paths': 24, 'in': 12, 'minors': 20, 'iv': 15, 'widths': 41, 'well': 40, 'quasi': 26, 'ordering': 23}


In [22]:
vectorizer = CountVectorizer()
X = vectorizer.fit_transform(content) #X is Term-document matrix
X.toarray()

array([[1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2,
        1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0],
       [0, 1, 0, 0, 0, 1, 2, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1,
        0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
        0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1,
        0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1,
        0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1],

In [24]:
vector1=X[0]
vector2=X[1]
vector3=X[2]
vector4=X[3]
vector5=X[4]
vector6=X[5]
vector7=X[6]
vector8=X[7]

In [30]:
q=["Human-based review of computer systems"]
Y = vectorizer.fit_transform(q) 
Y.toarray()


array([[1, 1, 1, 1, 1, 1]], dtype=int64)

In [31]:
vectorQ=Y[0]


In [51]:
import math
def cosine_similarity(vector1,vector2):
  dot=0
  # Calculate numerator of cosine similarity
  for i in range(vector1.shape[1]):
        dot =dot+ (vector1[i] * vector2[i])
        
  # Normalize the first vector
  sum_vector1 = 0.0
  for i in range(vector1.shape[1]):
        sum_vector1 += sum_vector1 + (vector1[i]*vector1[i])
  norm_vector1 = math.sqrt(sum_vector1)
  
  # Normalize the second vector
  sum_vector2 = 0.0
  for i in range(vector2.shape[1]):
    sum_vector2 += sum_vector2 + (vector2[i]*vector2[i] )
  norm_vector2 = math.sqrt(sum_vector2)
  
  return (dot/(norm_vector1*norm_vector2))


In [52]:
print('D1:',cosine_similarity(vector1,vectorQ))

ValueError: dimension mismatch

In [55]:
X=X.toarray()

In [56]:
#Apply SVD
U, S, V =np.linalg.svd(X)
S=np.diag(S)
#V=V[:5,:]

In [57]:
print(U.shape, S.shape, V.shape)

(8, 8) (8, 8) (42, 42)


In [58]:
S

array([[4.76655917, 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        ],
       [0.        , 3.40604955, 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        ],
       [0.        , 0.        , 3.27168236, 0.        , 0.        ,
        0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.        , 2.73486607, 0.        ,
        0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.        , 2.57119697,
        0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        2.18006813, 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 1.99014906, 0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 1.47339678]])

In [59]:
U

array([[ 0.11657869,  0.32576064,  0.05509811, -0.88983304,  0.23137502,
        -0.17815045,  0.01002343, -0.00884995],
       [ 0.5106581 , -0.10619854, -0.50400399, -0.13419595,  0.00574248,
         0.64856715, -0.09090981,  0.16427016],
       [ 0.6026951 ,  0.63965956,  0.32649203,  0.29868039, -0.16355496,
        -0.03502934,  0.02521104, -0.05634146],
       [ 0.336086  , -0.1255377 , -0.59744926,  0.07398181, -0.10422966,
        -0.68773113,  0.09196801, -0.12873041],
       [ 0.25649197, -0.2319602 ,  0.17444331,  0.14990442,  0.66768101,
        -0.10551434, -0.57058441, -0.21214796],
       [ 0.27737097, -0.32285035,  0.24940366,  0.04647805,  0.40073154,
        -0.00970128,  0.75109781,  0.17217085],
       [ 0.31858528, -0.52006122,  0.42519186, -0.23525341, -0.52101598,
        -0.13655898, -0.23984144,  0.21042228],
       [ 0.07227147, -0.17081057,  0.07733524, -0.12461785, -0.17600345,
         0.20867719,  0.18789047, -0.91338055]])

In [60]:
V

array([[ 2.44576184e-02,  1.93279963e-01,  2.44576184e-02, ...,
         3.04085012e-01,  6.68375791e-02,  6.68375791e-02],
       [ 9.56417785e-02,  3.51135067e-02,  9.56417785e-02, ...,
         1.19764352e-01, -1.52687508e-01, -1.52687508e-01],
       [ 1.68409090e-02,  2.29754545e-01,  1.68409090e-02, ...,
        -2.36869334e-01,  1.29961230e-01,  1.29961230e-01],
       ...,
       [ 5.26028712e-02, -2.77634420e-01, -2.69004765e-04, ...,
         8.27293387e-01,  5.09054623e-02,  5.09054623e-02],
       [-1.46428981e-02, -2.13534041e-01, -1.09408234e-01, ...,
        -1.76525298e-02,  8.84692937e-01, -1.15307063e-01],
       [-1.46428981e-02, -2.13534041e-01, -1.09408234e-01, ...,
        -1.76525298e-02, -1.15307063e-01,  8.84692937e-01]])

In [61]:
print(U.dot(S).dot(V))

ValueError: shapes (8,8) and (42,42) not aligned: 8 (dim 1) != 42 (dim 0)

In [62]:
U.transpose().dot(U)

array([[ 1.00000000e+00, -1.20464404e-16,  4.58868062e-17,
         1.89828088e-16, -1.06660932e-16, -3.12331035e-16,
         8.11418378e-18, -5.98114954e-17],
       [-1.20464404e-16,  1.00000000e+00,  2.61006413e-16,
        -2.82635336e-17, -9.98429629e-17,  2.83348805e-16,
        -4.66389050e-17,  6.64178617e-17],
       [ 4.58868062e-17,  2.61006413e-16,  1.00000000e+00,
        -3.91904787e-18, -3.53581341e-16,  5.54221667e-17,
         3.84250660e-17, -2.56431542e-16],
       [ 1.89828088e-16, -2.82635336e-17, -3.91904787e-18,
         1.00000000e+00,  1.23965629e-16,  1.41951260e-16,
         3.77669672e-17, -1.12107197e-16],
       [-1.06660932e-16, -9.98429629e-17, -3.53581341e-16,
         1.23965629e-16,  1.00000000e+00, -7.47066902e-17,
         3.24993081e-16, -3.85908979e-17],
       [-3.12331035e-16,  2.83348805e-16,  5.54221667e-17,
         1.41951260e-16, -7.47066902e-17,  1.00000000e+00,
         2.09699070e-16,  7.45734811e-18],
       [ 8.11418378e-18, -4.663890

In [63]:
k=2
UK=U[:,:k]
SK=S[:k, :k]
VK=V[:k, :]
print(UK)
print(VK)
print(SK)

[[ 0.11657869  0.32576064]
 [ 0.5106581  -0.10619854]
 [ 0.6026951   0.63965956]
 [ 0.336086   -0.1255377 ]
 [ 0.25649197 -0.2319602 ]
 [ 0.27737097 -0.32285035]
 [ 0.31858528 -0.52006122]
 [ 0.07227147 -0.17081057]]
[[ 0.02445762  0.19327996  0.02445762  0.05381072  0.1315911   0.12644238
   0.25288477  0.07050914  0.02445762  0.05381072  0.14019079  0.1509
   0.05819103  0.1509      0.05819103  0.06683758  0.02445762  0.02445762
   0.12644238  0.07050914  0.08199977  0.59005782  0.10713349  0.06683758
   0.05819103  0.07050914  0.06683758  0.05381072  0.07050914  0.17764263
   0.12229567  0.23357587  0.12644238  0.12644238  0.23844413  0.17764263
   0.07050914  0.17883932  0.05381072  0.30408501  0.06683758  0.06683758]
 [ 0.09564178  0.03511351  0.09564178 -0.06810242  0.06446239  0.18780101
   0.37560203 -0.03685727  0.09564178 -0.06810242 -0.29762401  0.28344279
  -0.09478733  0.28344279 -0.09478733 -0.15268751  0.09564178  0.09564178
   0.18780101 -0.03685727 -0.20283668 -0.22699

In [64]:
Ak=UK.dot(SK).dot(VK)
print(Ak)

[[ 0.11971058  0.14636209  0.11971058 -0.04566201  0.14464713  0.27863731
   0.55727462 -0.00171478  0.11971058 -0.04566201 -0.25232966  0.39834789
  -0.07283639  0.39834789 -0.07283639 -0.13227522  0.11971058  0.11971058
   0.27863731 -0.00171478 -0.17949327  0.076022    0.02493655 -0.13227522
  -0.07283639 -0.00171478 -0.13227522 -0.04566201 -0.00171478  0.02322177
  -0.0222815   0.30357385  0.27863731  0.27863731  0.16013891  0.02322177
  -0.00171478 -0.25077362 -0.04566201  0.30185908 -0.13227522 -0.13227522]
 [ 0.02493655  0.45775812  0.02493655  0.15561354  0.29698637  0.23984022
   0.47968045  0.18495696  0.02493655  0.15561354  0.44889171  0.26477677
   0.17592797  0.26477677  0.17592797  0.21791789  0.02493655  0.02493655
   0.23984022  0.18495696  0.27296374  1.51835623  0.27204983  0.21791789
   0.17592797  0.18495696  0.21791789  0.15561354  0.18495696  0.45700678
   0.32709567  0.51189005  0.23984022  0.23984022  0.57138173  0.45700678
   0.18495696  0.5494594   0.15561354